# -*- coding: utf-8 -*-
"""pandaspython16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxpLo7F2NzFEZVtKiazs6KmkSKebwBAg
"""

print("Let's get started")

import pandas as pd

df=pd.read_csv("C:\Users\anish\Downloads\CardioGoodFitness-1.csv")

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/CardioGoodFitness-1.csv")

df.sample(10)

df.shape

df.dtypes

df.info()

df.isnull().sum()

df.sum()

df.sample(25)

df.describe()

df.describe()

df.describe(include="all")

