# -*- coding: utf-8 -*-
"""PandasNumpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VQrKZFB5PWhT_yn4JmLqnrnrJIt3x5Ae
"""

import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/hotel_bookings.csv")

df.shape

df.sample(111)

df.sample

df.dtypes

df.info()

df.isnull().sum()

df.sample(1110)



df.describe(include="all")

import numpy as np

labels=['w','x','y','z']
sample_list=[100,200,300,400]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}

pd.Series(data=sample_list)

pd.Series(data=sample_list,index=labels)

pd.Series(sample_list,array)

pd.Series(dict)

sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

sports1['cricket']

sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

sports1+sports2

df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

df1["Score3"]

df1[["Score1", "Score2","Score3"]]

df1['Score6']=df1['Score1']+df1['Score2']

df1

df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

df["ID"]

df[["ID","Name"]]

df=df.drop("ID",axis=1)

df

df.drop(3)

df.drop(2,axis=0)

